[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Redirect rules for clean URLs and SEO
[[redirects]]
  from = "/posts/*"
  to = "/:splat"
  status = 301

# Handle SPA routing for search
[[redirects]]
  from = "/search"
  to = "/search/index.html"
  status = 200

# 404 page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"